# Generated by Django 2.2 on 2020-07-21 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(max_length=3000, verbose_name='Описание')),
                ('status', models.CharField(default='new', max_length=40)),
                ('create_at', models.DateTimeField(blank=True, default='null', null=True, verbose_name='Дата выполнения')),
            ],
        ),
    ]
