# Generated by Django 2.2 on 2020-07-22 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='name',
            field=models.TextField(default=False, max_length=1000, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='article',
            name='create_at',
            field=models.DateField(blank=True, default=False, null=True, verbose_name='Дата выполнения'),
        ),
    ]
