# Generated by Django 2.2 on 2020-07-22 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_auto_20200722_0529'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='create_at',
            field=models.DateField(blank=True, null=True, verbose_name='Дата выполнения'),
        ),
    ]
